- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - Small help message fix

diff --git a/mrnet/mrnet/configure b/mrnet/mrnet/configure
--- a/mrnet/mrnet/configure
+++ b/mrnet/mrnet/configure
@@ -2245,8 +2245,8 @@ _ACEOF
   LIBS="-lfl $LIBS"
 
 else
-  { { echo "$as_me:$LINENO: error: Can't find flex library libfl. Must specify with --with-libfl" >&5
-echo "$as_me: error: Can't find flex library libfl. Must specify with --with-libfl" >&2;}
+  { { echo "$as_me:$LINENO: error: Can't find flex library libfl. Must specify proper directory with --with-libfldir" >&5
+echo "$as_me: error: Can't find flex library libfl. Must specify proper directory with --with-libfldir" >&2;}
    { (exit 1); exit 1; }; }
 fi
 
