Test

diff --git a/.github/workflows/binary-tests.yaml b/.github/workflows/binary-tests.yaml
--- a/.github/workflows/binary-tests.yaml
+++ b/.github/workflows/binary-tests.yaml
@@ -8,17 +8,17 @@
 name: Regression tests for known binaries
 
 on:
-  pull_request:
-     types: [opened, synchronize, reopened, ready_for_review]
-     branches:
-        - master
-     paths:
-       - '**.h'
-       - '**.C'
-       - '**.c'
-       - '**.cmake'
-       - '**CMakeLists.txt'
-       - 'tests/*'
+#  pull_request:
+#     types: [opened, synchronize, reopened, ready_for_review]
+#     branches:
+#        - master
+#     paths:
+#       - '**.h'
+#       - '**.C'
+#       - '**.c'
+#       - '**.cmake'
+#       - '**CMakeLists.txt'
+#       - 'tests/*'
   workflow_dispatch:
 
 concurrency:
@@ -29,69 +29,68 @@ permissions: {}
 
 jobs:
 
-  # Don't run the check if the PR is a draft
-  check-if-needed:
+  is-needed:
     runs-on: ubuntu-latest
-    if: ${{ github.event.pull_request.draft == false }}
-    steps:
-      - shell: bash
-        run: true
-
-  get-oses:
-    runs-on: ubuntu-latest
-    needs: check-if-needed
-    outputs:
-      latest: ${{ steps.all.outputs.latest }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
-
-      - id: all
-        uses: ./.github/actions/os-versions
-
-  get-compilers:
-    runs-on: ubuntu-latest
-    needs: check-if-needed
-    outputs:
-      all: ${{ steps.compilers.outputs.value }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
-        
-      - id: compilers
+    uses: $/.github/workflows/check-if-needed.yaml@main
+  say-hi:
+     runs-on: ubuntu-latest
+     needs: is-needed
+     steps:
         shell: bash
         run: |
-          set -ex
-          script="./.github/scripts/compiler_configs.py"
-          names=$(python3 ${script} --print-names)
-          echo "value=${names}" >> $GITHUB_OUTPUT
-
-  binary-tests:
-    runs-on: ubuntu-latest
-    needs: [get-oses, get-compilers]
-    strategy:
-      fail-fast: false
-      matrix:
-        os: ${{ fromJson(needs.get-oses.outputs.latest) }}
-        compiler: ${{ fromJson(needs.get-compilers.outputs.all) }}
-    permissions:
-      packages: read
-    container:
-      image: ghcr.io/dyninst/amd64/${{ matrix.os }}-base:latest
-      credentials:
-        username: ${{ github.actor }}
-        password: ${{ secrets.github_token }}
-    name: Binary tests (${{ matrix.os }}, ${{ matrix.compiler }})
-    steps:
-      - name: Checkout Dyninst
-        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
-        with:
-          path: "src"  # relative to ${GITHUB_WORKSPACE}
-
-      - name: Build Dyninst
-        uses: ./src/.github/actions/build
-        with:
-          os: ${{ matrix.os }}
-          compiler: ${{ matrix.compiler }}
-          src-dir: "${GITHUB_WORKSPACE}/src"
-          tests: "ALL"
+           echo ${{ needs.is-needed.outputs }}
+#    outputs:
+#      latest: ${{ steps.all.outputs.latest }}
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+#
+#      - id: all
+#        uses: ./.github/actions/os-versions
+#
+#  get-compilers:
+#    runs-on: ubuntu-latest
+#    needs: check-if-needed
+#    outputs:
+#      all: ${{ steps.compilers.outputs.value }}
+#    steps:
+#      - name: Checkout
+#        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+#        
+#      - id: compilers
+#        shell: bash
+#        run: |
+#          set -ex
+#          script="./.github/scripts/compiler_configs.py"
+#          names=$(python3 ${script} --print-names)
+#          echo "value=${names}" >> $GITHUB_OUTPUT
+#
+#  binary-tests:
+#    runs-on: ubuntu-latest
+#    needs: [get-oses, get-compilers]
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        os: ${{ fromJson(needs.get-oses.outputs.latest) }}
+#        compiler: ${{ fromJson(needs.get-compilers.outputs.all) }}
+#    permissions:
+#      packages: read
+#    container:
+#      image: ghcr.io/dyninst/amd64/${{ matrix.os }}-base:latest
+#      credentials:
+#        username: ${{ github.actor }}
+#        password: ${{ secrets.github_token }}
+#    name: Binary tests (${{ matrix.os }}, ${{ matrix.compiler }})
+#    steps:
+#      - name: Checkout Dyninst
+#        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+#        with:
+#          path: "src"  # relative to ${GITHUB_WORKSPACE}
+#
+#      - name: Build Dyninst
+#        uses: ./src/.github/actions/build
+#        with:
+#          os: ${{ matrix.os }}
+#          compiler: ${{ matrix.compiler }}
+#          src-dir: "${GITHUB_WORKSPACE}/src"
+#          tests: "ALL"
