move from cmake-format to gersemi

diff --git a/.github/workflows/cmake-formatting.yaml b/.github/workflows/cmake-formatting.yaml
--- a/.github/workflows/cmake-formatting.yaml
+++ b/.github/workflows/cmake-formatting.yaml
@@ -27,17 +27,60 @@ jobs:
       run: |
         sudo apt-get update
         sudo apt-get install -y python3-pip
-        python3 -m pip install cmake-format
+        python3 -m pip install gersemi
 
-    - name: cmake-format
+    - name: gersemi
       shell: bash
       run: |
-        set +e
-        cmake-format -i $(find . -type f | egrep 'CMakeLists.txt|\.cmake$')
-        if [ $(git diff | wc -l) -gt 0 ]; then
-          echo -e "\nError! CMake files not formatted."
-          echo -e "\nRun the following to fix:"
-          for f in $(git diff --name-only); do echo -e "  cmake-format -i $f"; done
-          echo
+        function PrintHeader()
+        {
+          delim='----------------------------------------'
+          printf '\n\n%s\n' "$delim"
+          printf '%s\n' "$@"
+          printf '%s\n' "$delim"
+        }
+
+        # use process substitution to avoid early exit if grep or git fail
+        # store the cmake files into cmakeFiles array
+        mapfile -t cmakeFiles < <( git ls-files | grep -E '(^|/)CMakeLists\.txt$|\.cmake$' )
+
+        # store stdout and stderr lines of 'gersemi --check' into gersemiCheck array
+        # adding a line '@@@rc=<RETURN_CODE>' to get the rc from the gersemi process substitution
+        mapfile -t gersemiCheck < <( rc=0; gersemi --check "${cmakeFiles[@]}" 2>&1|| rc=$?; echo "@@@rc=$rc" )
+        gersemiRc=${gersemiCheck[-1]#@@@rc=}
+        unset "gersemiCheck[-1]"
+
+        reformatFiles=( )
+        warnings=( )
+        reformats=( )
+        for line in "${gersemiCheck[@]}"; do
+          case "$line" in
+            *' would be reformatted')
+              reformats+=( "$line" )
+              path=${line% would be reformatted}
+              reformatFiles+=( "${path#"$PWD"/}" )
+              ;;
+            *)
+              warnings+=( "$line" )
+              ;;
+          esac
+        done
+
+        PrintHeader "Reformatting required from:  gersemi --check ..."
+        if [ ${#reformats[@]} -gt 0 ]; then
+            printf '%s\n' "${reformats[@]}"
+        fi
+
+        PrintHeader "Warnings from:  gersemi --check ..."
+        if [ ${#warnings[@]} -gt 0 ]; then
+          printf '%s\n' "${warnings[@]}"
+        fi
+
+        if [ "$gersemiRc" != 0 ]; then
+          PrintHeader "ERROR: gersemi --check failed with rc=$gersemiRc" \
+                      "To fix run the following command:"
+          printf '%s\n' "gersemi --in-place ${reformatFiles[*]}"
+          PrintHeader "gersemi --diff ${reformatFiles[*]}"
+          gersemi --diff "${reformatFiles[@]}"
           exit 1
         fi
